version: '3.9'

services:
  map-service-web-nginx:
    user: root
    image: nginx:1.25.3
    restart: always
    container_name: ${MAP_SERVICE_WEB_NGINX_NAME}
    hostname: ${MAP_SERVICE_WEB_NGINX_NAME}
    env_file:
      - .env
    ports:
      - ${MAP_SERVICE_WEB_NGINX_PORT}:80
    volumes:
      - ./sample:/usr/share/nginx/html #임시
      - ./config/nginx:/etc/nginx/conf.d

  map-service-web-npm:
    user: root
    image: node:lts-alpine3.19
    restart: always
    container_name: ${MAP_SERVICE_WEB_NODE_NAME}
    hostname: ${MAP_SERVICE_WEB_NODE_NAME}
    env_file:
      - .env
    ports:
      - ${MAP_SERVICE_WEB_NODE_PORT}:8080
    tty: true
    stdin_open: true
    volumes:
      - ./react:/app
    # /bin/sh

